application: vimrcgenerator
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /.*\.html
  static_files: index.html
  upload: index.html
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: index.py
